apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-pipeline
  name: data-pipeline
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 1323
      name: data-pipeline
  selector:
    app: data-pipeline
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-pipeline
  template:
    metadata:
      labels:
        app: data-pipeline
    spec:
      containers:
        - name: data-pipeline-container
          image: jeffreylean/data-pipeline
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 1323
          volumeMounts:
            - name: local
              mountPath: /Users/RM8005-jeffrey/Project/air-asia
      volumes:
        - name: local
          hostPath:
            path: /Users/RM8005-jeffrey/Project/air-asia
